language: ruby

rvm:
  - 2.2.4

gemfile:
  - gemfiles/Gemfile.rails-4.2-stable

services:
  - mongodb

sudo: false

cache: bundler

env:
  matrix:
    - DEVISE_ORM=mongoid
    - DEVISE_ORM=active_record

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script: "bundle exec rake test"

branches:
  only:
    - rails424ruby224
